site_name: TECH BLOGS
site_url: https://techblogs.rathnaschools.com
site_description: >-
  An interesting site which contains latest tech news and blogs

nav:
    - How to install UBUNTU OS?: index.md
    - Top 10 Programming languages to learn in 2022: top-10-programming-languages-to-learn-in-2022.md

markdown_extensions:
  - attr_list
  - md_in_html

theme:
  name: material
  custom_dir: overrides